version: "3"
services:
  config-server:
    image: devbhuwan/config-server
    env_file:
      - env/config-server.env
    volumes:
      - ./configs:$HOME/configs
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - 8888:8888
  service-discovery:
    image: devbhuwan/service-discovery
    env_file:
      - env/service-discovery.env
    networks:
      - backend
    depends_on:
      - config-server
    ports:
      - 8761:8761
#  api-gateway:
#    image: devbhuwan/api-gateway
#    env_file:
#      - env/api-gateway.env
#    networks:
#      - backend
#    depends_on:
#      - service-discovery
#      - config-server
networks:
  backend:
