version: "3"
services:
  config-server:
    image: devbhuwan/config-server
    build:
      context: ../../ # root directory for build
      dockerfile: devops/.docker/spring-boot/Dockerfile
      args:
        - JAR_FILE=config-server/target/config-server-1.0-SNAPSHOT.jar
  service-discovery:
    image: devbhuwan/service-discovery
    build:
      context: ../../
      dockerfile: devops/.docker/spring-boot/Dockerfile
      args:
        - JAR_FILE=service-discovery/target/service-discovery-1.0-SNAPSHOT.jar
  api-gateway:
    image: devbhuwan/api-gateway
    build:
      context: ../../
      dockerfile: devops/.docker/spring-boot/Dockerfile
      args:
        - JAR_FILE=api-gateway/target/api-gateway-1.0-SNAPSHOT.jar