version: "3"
services:
  service-discovery:
    image: devbhuwan/service-discovery
    env_file:
      - env/service-discovery.env
    ports:
      - 8761:8761
  config-server:
    image: devbhuwan/config-server
    env_file:
      - env/config-server.env
    links:
      - service-discovery:service-discovery
    ports:
      - 8888:8888